name: Python Tests

on:
  push:

  pull_request:

jobs:

  tests:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3

        with:
          environment-file: environment.yml
          activate-environment: research

      - name: Run Tests

        shell: bash -l {0}

        run: pytest